title:              LibreELEC
email:
description:        Just enough OS for KODI
author:             LibreELEC
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://cvh.github.io"
default_header_logo: "img/bg-index.jpg" # relative path to default header logo

# Social Profiles
twitter_username:   LibreELEC
github_username:    LibreELEC/LibreELEC.tv
facebook_username:
instagram_username:  
linkedin_username:
reddit_url: https://www.reddit.com/r/LibreELEC
youtube_url: https://www.youtube.com/channel/UC7FSO0rXOtO6w_poBLvvjDw
wiki_url: https://libreelec.wiki

# Add your google-analytics ID here to activate google analytics
google_analytics:  # out your google-analytics code

# LE
post_limit: 5 # number of posts shown
post_subtitle_limit: 40 # number of words included at post preview

# Build settings
markdown:           kramdown
paginate:           6
paginate_path:      "/posts/page/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# LE downloads

# download url
le_download_url: https://releases.libreelec.tv

# LE10.0
release_date_le_10_0: 2021.08
kodi_version_le_10_0: 19.1
le_version_download_10_0: 10.0.0
le_version_name_10_0: 10.0 # 10.0 RC1
kernel_version_le_10_0: 5.10.x

# LE9.2
release_date_le_9_2: 2020.11
kodi_version_le_9_2: 18.9
le_version_download_9_2: 9.2.6
le_version_name_9_2: 9.2
kernel_version_le_9_2: 5.1.x
kernel_version_le_rpi_9_2: 4.19.x
kernel_version_le_rk_9_2: 4.4.x

# LE9.0 Amlogic
release_date_le_9_0: 2020.05
kodi_version_le_9_0: 18.2
le_version_download_9_0: 9.0.2
le_version_name_9_0: 9.0
kernel_version_le_9_0: 4.19.x
kernel_version_le_aml_9_0: 3.14.x