title:              LibreELEC
email:
description:        Just enough OS for KODI
author:             Start Bootstrap
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://cvh.github.io"
default_header_logo: "img/bg-index.jpg" # relative path to default header logo

# Social Profiles
twitter_username:   LibreELEC
github_username:    LibreELEC/LibreELEC.tv
facebook_username:
instagram_username:  
linkedin_username:
reddit_url: https://www.reddit.com/r/LibreELEC
youtube_url: https://www.youtube.com/channel/UC7FSO0rXOtO6w_poBLvvjDw

# Add your google-analytics ID here to activate google analytics
google_analytics:  # out your google-analytics code

# LE
post_limit: 4 # number of posts shown
post_subtitle_limit: 40 # number of words included at post preview

# Build settings
markdown:           kramdown
paginate:           4
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
